### ISSUE TITLE
Your hosting is kinda frigged

### ISSUE THREAD

**Issue by Leonetienne** [SiGe11/clock#1]
I really have no idea why, but on your gists.rawgit.com page the url parameters have stopped working. I can't set a custom style, nor format. The clock keeps ticking tho...

Maybe github disabled parameter-forwarding...? My browser reports no errors or failed-to-load resources.

Since i need this for my OBS setup, i've forked it to fix it... But it just works, locally that is. So i'm just using a local instance for now...
Just wanted to let you know.

**Comment by SiGe11** [comment]
Thank you to note it.
However, I can't reproduce this behavior. For me, it works correctly.

**Comment by Leonetienne** [comment]
If you can't reproduce it, imma close it.
